# 1

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.intersect1d(a,b)
c

array([2, 4])

# 2

In [10]:
a = np.arange(1,16)
a
a = a.reshape(3,5).transpose()
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# 3

In [17]:
a = a.transpose().flatten()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# 4

In [28]:
a = np.arange(1,16).reshape(3,5).transpose()
b = a.reshape(5,3,1)
b

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

# 5

In [29]:
b.reshape(5,3)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])