In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.where(arr%2 == 1, -10, arr)
arr

array([  0, -10,   2, -10,   4, -10,   6, -10,   8, -10])

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
arr = np.array([3,1, 6, 17, 8, 42, 10, 39, 25, 12, 14,42])
arr = np.array([i for i in arr if(i>=5 and i<=12)])
arr

array([ 6,  8, 10, 12])

In [7]:
arr = np.arange(9).reshape(3,3)
arr[[0,1],:]=arr[[1,0],:]
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])