# 1

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.intersect1d(a,b)                                         #np.intersect1d will return an intersection of two arrays
c

array([2, 4])

# 2

In [10]:
a = np.arange(1,16)
a
a = a.reshape(3,5).transpose()                                  # np.transpose will return the transpose of a matrix
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# 3

In [17]:
a = a.transpose().flatten()                                         # np.flatten() will return an 1-dimensional array
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# 4

In [28]:
a = np.arange(1,16).reshape(3,5).transpose()
b = a.reshape(5,3,1)
b

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

# 5

In [29]:
b.reshape(5,3)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# 6

First, we get an indices which can sort the a, than we use these indices to compare a and b, it won't break the order of a

In [60]:
a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5]) 

c = np.argsort(a)                                   # np.argsort(a) will returns the indices that would sort an array.
d = []                                              # Use d to store the indices in a of the numbers that appear in a and b at the same time
for i in b:
    for p in c:
        if(i == a[p]):
            d.append(p)
        elif(i < a[p]):                             #
            break
result = np.delete(a,d)
result

array([ 7, 15,  1,  8])

# 7

In [43]:
import pandas as pd
import numpy as np 
 
# supress scientific notation 
np.set_printoptions(suppress = True) 
 
# read the data file from GitHub and convert to a NumPy ndarray object 
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below 
# with a link to the “raw” version of the file you pushed to your online GitHub repository 
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/azsxscdvfb/AIM-5001/main/week6/Module6_Data.csv').to_numpy() 
 
# verify you have an ndarray object 
type(nyc_water) 

numpy.ndarray

## 7.1
### What is the maximum yearly NYC consumption of water in millions of gallons per day? 

In [61]:
max_yearly_cons_index = np.argmax(nyc_water[:,2])
print("Thw maximum yearly NYC consumption of water in millions of gallons per day is", nyc_water[0,max_yearly_cons_index], ",the consumption is", nyc_water[2,max_yearly_cons_index])

Thw maximum yearly NYC consumption of water in millions of gallons per day is 1979.0 ,the consumption is 1981.0


## 7.2
### How many calendar years are represented within this data set?

In [52]:
print("There are", nyc_water.shape[0],"calendar years")

There are 39 calendar years


## 7.3
### What is the mean and the standard deviation of the per capita daily water consumption?

In [56]:
print("The standard deviation is", nyc_water[:,3].std().round(4),", the mean is", nyc_water[:,3].mean().round(4))

The standard deviation is 31.5189 , the mean is 160.3077


## 7.4
### What is the increase or decrease in population from year to year?  

In [57]:
pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
